resources:
- name: cicd_master
  type: syncRepo
- name: shippable-ami-builder
  type: integration
  integration: shippable-ami-builder
- name: keights-v1.11
  type: gitRepo
  integration: github
  versionTemplate:
    sourceName: cloudboss/keights
    buildOnCommit: false
    buildOnPullRequest: true
    depth: 10
- name: version-v1.11.2-rc
  type: version
  versionTemplate:
    versionName: v1.11.2

jobs:
- name: bump-version
  type: release
  bump: rc
  dependencyMode: chrono
  steps:
  - TASK: managed
  - IN: version-v1.11.2-rc
  - IN: keights-v1.11
- name: keights_build
  type: runSh
  steps:
  - IN: keights-v1.11
  - IN: bump-version
  - TASK:
      runtime:
        options:
          imageName: golang
          imageTag: 1.11
      script:
        - make test
